# Quick Commit Script
# Pøidává informace o nástroji do TXT reportù

$gitPath = "C:\Program Files\Microsoft Visual Studio\18\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd\git.exe"

Set-Location "C:\Users\pbalas\source\repos\CompareProxyCsFile"

Write-Host "Adding GitHub link to reports..." -ForegroundColor Green

& $gitPath add -A
& $gitPath commit -m "Add tool info and GitHub link to reports

- Added 'Generated by: CompareProxyCsFile v1.0.0' to report headers
- Added GitHub repository link to both normal and error reports
- Updated README.md example output to reflect changes
- Makes it easy to identify how the report was generated"

& $gitPath push

Write-Host ""
Write-Host "? Changes committed and pushed!" -ForegroundColor Green
Write-Host ""
